# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and publish to Python package repository
      uses: JRubics/poetry-publish@v2.0
      with:
        repository_name: "praetorian-api-client"
        repository_url: "https://github.com/Praetorian-Defence/praetorian-api-client"
        pypi_token: ${{ secrets.PYPI_TOKEN }}
